# Generated by Django 5.2.6 on 2025-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_created_at_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
