# Generated by Django 5.2.6 on 2025-09-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groq_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="role",
        ),
    ]
